# Generated by Django 3.1 on 2020-11-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField(blank=True, null=True)),
                ('mess', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
