# Generated by Django 3.1 on 2020-11-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('describe', models.CharField(blank=True, max_length=255, null=True, verbose_name='message')),
            ],
        ),
        migrations.DeleteModel(
            name='destination',
        ),
    ]
